# Generated by Django 4.1.5 on 2023-01-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(help_text='Enter snack description'),
        ),
    ]
